
  inventory:
    image: "IMAGE_REGISTRY/inventory:VERSION"
    #image: "python:VERSION"
    links:
        - mongodb:mongodb
        - redis:redis
    command: ["grpc", "spaceone.inventory", "-c", "/opt/inventory.yml"]
    #command: ["sleep", "36000"]
    volumes:
      - ./conf/inventory.yml:/opt/inventory.yml
      #- ../../../:/opt/
    depends_on:
      - redis

