
  identity:
    image: "IMAGE_REGISTRY/identity:VERSION"
    links:
        - mongodb:mongodb
        - redis:redis
    command: ["grpc", "spaceone.identity", "-c", "/opt/identity.yml"]
    volumes:
      - ./conf/identity.yml:/opt/identity.yml
    depends_on:
      - redis

