
  statistics:
    image: "IMAGE_REGISTRY/statistics:VERSION"
    links:
        - mongodb:mongodb
        - redis:redis
    command: ["grpc", "spaceone.statistics", "-c", "/opt/statistics.yml"]
    volumes:
      - ./conf/statistics.yml:/opt/statistics.yml
    depends_on:
      - redis

