GLOBAL:
    DATABASES:
        default:
            db: power_scheduler
            host: mongodb
            username: power_scheduler
            password: power_scheduler_password

    CACHES:
        default:
            backend: spaceone.core.cache.redis_cache.RedisCache
            host: redis 
            port: 6379
            db: 0

    CONNECTORS:
        IdentityConnector:
            endpoint:
                v1: grpc://identity:50051

        PluginConnector:
            endpoint:
                v1: grpc://plugin:50051

        SecretConnector:
            endpoint:
                v1: grpc://secret:50051

        RepositoryConnector:
            endpoint:
                v1: grpc://repository:50051
    QUEUES:
      controller_q:
        backend: spaceone.core.queue.redis_queue.RedisQueue
        host: redis
        port: 6379
        channel: controller

    SCHEDULERS:
      job_starter_scheduler:
        backend: spaceone.power_scheduler.scheduler.job_starter_scheduler.JobStarterScheduler
        queue: controller_q
        interval: 5
      power_control_scheduler:
        backend: spaceone.power_scheduler.scheduler.power_control_scheduler.PowerControlScheduler
        queue: controller_q
        interval: 1

    TOKEN_INFO:
      config:
        host: 'consul'
      protocol: consul
    uri: debug/supervisor/TOKEN
    HANDLERS:
        authentication:
        - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
          uri: grpc://identity:50051/v1/Domain/get_public_key

