
  inventory-worker:
    image: "IMAGE_REGISTRY/inventory:VERSION"
    #image: "python" 
    links:
        - mongodb:mongodb
        - redis:redis
    command: ["scheduler", "spaceone.inventory", "-c", "/opt/inventory.yml"]
    #command: ["sleep", "360000"] 
    volumes:
      - ./conf/inventory-worker.yml:/opt/inventory.yml
        #- ../../../:/opt/
    depends_on:
      - redis

